const $ = id => document.getElementById(id);
const DAYS = ['周日','周一','周二','周三','周四','周五','周六'];
const DAY_ORDER = [1,2,3,4,5,6,0];
const pad = n => String(n).padStart(2,'0');
const dateKey = (d = new Date()) => `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback } catch { return fallback } };
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
const toast = msg => { $('toast').textContent=msg; $('toast').classList.add('show'); setTimeout(()=>$('toast').classList.remove('show'),1500) };
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`);

let settings = read('tri-settings',{termName:'',termStart:'',termWeeks:18,periodCount:12});
let courses = read('tri-courses',[]);
let checks = read('tri-checks',{});
let viewWeekNumber = getCurrentWeek() || 1;
let pdfDrafts = [];
const PLAN_START = new Date('2026-09-01T00:00:00');
const PLAN_END = new Date('2027-08-31T00:00:00');
const DAY_MS = 86400000;
const nowForPlan = new Date(); nowForPlan.setHours(0,0,0,0);
let selectedPlanDate = nowForPlan < PLAN_START ? new Date(PLAN_START) : nowForPlan > PLAN_END ? new Date(PLAN_END) : nowForPlan;
let resources = read('tri-resources',[]);
let planChecks = read('tri-plan-checks',{});
let mathRoute = localStorage.getItem('tri-math-route') || 'zhangyu';
let politicsMode = localStorage.getItem('tri-politics-mode') || 'light';
let courseCatalog = read('tri-course-catalog',{math:[],politics:[]});
let smartSchedules = read('tri-smart-schedules',{math:{},politics:{}});
let courseProgress = read('tri-course-progress',{});
let smartConfig = read('tri-smart-config',{math:{start:'2026-09-01',minutes:120,weekdays:[1,2,3,4,5,6,0]},politics:{start:'2026-09-01',minutes:40,weekdays:[2,4,6,0]}});
const sessionCourseFiles = new Map();
const MUSCLES=[{id:'chest',name:'胸',title:'胸部训练'},{id:'back',name:'背',title:'背部训练'},{id:'shoulder',name:'肩',title:'肩部训练'},{id:'legs',name:'腿',title:'腿部训练'},{id:'abs',name:'腹',title:'腹部训练'}];
let fitnessSettings=read('tri-fitness-settings',{start:'2026-09-01',weeklyRest:[0],templates:{chest:'卧推 4×5–8\n上斜哑铃卧推 4×8–12\n器械夹胸 3×12–15\n双杠臂屈伸 3组',back:'辅助引体 3×8–10\n高位下拉 4×8–12\n坐姿划船 4×8–12\n面拉 3×15–20',shoulder:'哑铃推肩 4×6–10\n哑铃侧平举 5×12–20\n反向飞鸟 3×15\n面拉 3×15',legs:'深蹲 4×5–8\n罗马尼亚硬拉 4×8–10\n腿举 3×10–12\n腿弯举 3×12\n提踵 3×15',abs:'卷腹 3组\n悬垂举腿 3组\n腹轮 3组\n坡走 20分钟'}});
let fitnessEditingMuscle='chest';
let fitnessRest=read('tri-fitness-rest',{}),fitnessLogs=read('tri-fitness-logs',{});
let nutritionProfile=read('tri-nutrition-profile',{sex:'male',age:20,height:172,weight:72,activity:1.375,deficit:300});
let mealLogs=read('tri-meal-logs',{});
let selectedFood=null,plateDraft=[],plateDate='';
const inkState={english:{tool:'pen',color:'#20241f',width:3,strokes:[],active:null},math:{tool:'pen',color:'#20241f',width:3,strokes:[],active:null},politics:{tool:'pen',color:'#20241f',width:3,strokes:[],active:null}};

const starterWords = [
 ['abandon','/əˈbændən/ v.','放弃；抛弃','We should abandon assumptions that lack evidence.'],
 ['abstract','/ˈæbstrækt/ adj./n.','抽象的；摘要','The abstract summarizes the central argument.'],
 ['access','/ˈækses/ n./v.','使用权；获取','Students need access to reliable information.'],
 ['accommodate','/əˈkɒmədeɪt/ v.','容纳；适应；调节','The plan must accommodate changes in the timetable.'],
 ['acknowledge','/əkˈnɒlɪdʒ/ v.','承认；确认','The author acknowledges the limits of the study.'],
 ['acquire','/əˈkwaɪə(r)/ v.','获得；习得','Vocabulary is acquired through repeated exposure.'],
 ['adapt','/əˈdæpt/ v.','适应；改编','Successful learners adapt to new constraints.'],
 ['adequate','/ˈædɪkwət/ adj.','足够的；合格的','Adequate sleep supports memory and recovery.'],
 ['advocate','/ˈædvəkeɪt/ v.','提倡；拥护','Researchers advocate a more cautious approach.'],
 ['alter','/ˈɔːltə(r)/ v.','改变；更改','Small habits can alter long-term outcomes.'],
 ['ambiguous','/æmˈbɪɡjuəs/ adj.','模棱两可的','The statement remains ambiguous without context.'],
 ['anticipate','/ænˈtɪsɪpeɪt/ v.','预期；预料','Good planning anticipates possible conflicts.'],
 ['apparent','/əˈpærənt/ adj.','明显的；表面上的','The apparent decline may reflect measurement error.'],
 ['approach','/əˈprəʊtʃ/ n./v.','方法；接近','A systematic approach reduces anxiety.'],
 ['arbitrary','/ˈɑːbɪtrəri/ adj.','任意的；武断的','The deadline should not be arbitrary.'],
 ['assess','/əˈses/ v.','评估；评价','Weekly reviews help assess real progress.'],
 ['assume','/əˈsjuːm/ v.','假设；承担','Do not assume that a low score means failure.'],
 ['attain','/əˈteɪn/ v.','达到；获得','Consistency makes difficult goals attainable.'],
 ['attribute','/əˈtrɪbjuːt/ v.','归因于','The change cannot be attributed to one factor.'],
 ['coherent','/kəʊˈhɪərənt/ adj.','连贯的；一致的','A coherent answer is easier to defend.'],
 ['compelling','/kəmˈpelɪŋ/ adj.','令人信服的','The experiment provides compelling evidence.'],
 ['comprehensive','/ˌkɒmprɪˈhensɪv/ adj.','全面的；综合的','A comprehensive review includes multiple sources.'],
 ['concede','/kənˈsiːd/ v.','承认；让步','Even critics concede that the method has value.'],
 ['constrain','/kənˈstreɪn/ v.','限制；约束','Time and money constrain most student plans.'],
 ['controversial','/ˌkɒntrəˈvɜːʃl/ adj.','有争议的','The proposal remains controversial.'],
 ['conventional','/kənˈvenʃənl/ adj.','传统的；常规的','The result challenges conventional wisdom.'],
 ['decline','/dɪˈklaɪn/ n./v.','下降；拒绝','A gradual decline is more sustainable.'],
 ['derive','/dɪˈraɪv/ v.','获得；源自','The conclusion is derived from the data.'],
 ['distinguish','/dɪˈstɪŋɡwɪʃ/ v.','区分；辨别','We must distinguish correlation from causation.'],
 ['elaborate','/ɪˈlæbərət/ adj.; /ɪˈlæbəreɪt/ v.','复杂精细的；详细说明','Please elaborate on the mechanism.'],
 ['empirical','/ɪmˈpɪrɪkl/ adj.','实证的；经验的','The claim requires empirical support.'],
 ['enhance','/ɪnˈhɑːns/ v.','提高；增强','Practice can enhance reading efficiency.'],
 ['explicit','/ɪkˈsplɪsɪt/ adj.','明确的；直白的','Make the relationship between ideas explicit.'],
 ['facilitate','/fəˈsɪlɪteɪt/ v.','促进；使便利','The tool facilitates regular review.'],
 ['fundamental','/ˌfʌndəˈmentl/ adj.','根本的；基础的','Vocabulary is fundamental to comprehension.'],
 ['inevitable','/ɪnˈevɪtəbl/ adj.','不可避免的','Occasional setbacks are inevitable.'],
 ['interpret','/ɪnˈtɜːprɪt/ v.','解释；理解','The same result may be interpreted differently.'],
 ['maintain','/meɪnˈteɪn/ v.','维持；主张','The goal is to maintain strength while losing fat.'],
 ['notion','/ˈnəʊʃn/ n.','观念；看法','The evidence challenges that notion.'],
 ['preliminary','/prɪˈlɪmɪnəri/ adj.','初步的；预备的','These are only preliminary findings.'],
 ['substantial','/səbˈstænʃl/ adj.','大量的；实质的','The task requires substantial effort.'],
 ['sustain','/səˈsteɪn/ v.','维持；支撑','A realistic schedule is easier to sustain.']
].map((w,i)=>({id:`starter-${i}`,word:w[0],phonetic:w[1],meaning:w[2],example:w[3],status:'new',due:'',reps:0}));
let deck = read('tri-word-deck',starterWords);
if (!deck.length) deck = starterWords;
let wordQueue = [], wordIndex = 0, currentWord = null;

const phases = [
 [{name:'考研线',goal:'建立稳定底盘',items:['空课日优先数学 2 小时深度块','水课用于词汇或长难句 30–45 分钟','每日英语不断线，周日统一复盘','科研项目每周整理一个可追问点']},{name:'课程线',goal:'守住绩点与专业基础',items:['课程按真实周次进入计划','核心课当天收口 20 分钟','水处理、水力学等建立错题页','高权重作业提前拆分']},{name:'训练线',goal:'减脂保肌，不透支',items:['每周 3–4 次力量训练','胸、背、肩手臂，腿隔轮安排','训练 45–70 分钟封顶','蛋白 130–150g，睡眠 7h+']}],
 [{name:'考研线',goal:'从习惯转向产出',items:['数学英语提升到每日主线','逐步加入环境专业基础','每周输出错题复盘','保留完整真题阅读时段']},{name:'课程线',goal:'集中完成结课任务',items:['释放出的白天用于高权重任务','核心课整理成复试知识卡','零碎作业不占黄金学习块']},{name:'训练线',goal:'恢复完整轮换',items:['胸/背/肩/手臂循环','腿每两轮一次','每周一次低强度有氧','体重下降过快则增加热量']}],
 [{name:'考研线',goal:'不断线即可',items:['每天 45–90 分钟英语/数学保温','暂停扩展新战线','以单词和错题保持手感']},{name:'课程线',goal:'期末优先',items:['按考试权重分配复习块','优先补高风险科目','睡前写明次日第一任务']},{name:'训练线',goal:'维持与恢复',items:['每周三次全身训练','每次 45 分钟','不追重量和极端热量缺口']}]
];

function planIndex(date=selectedPlanDate){const d=new Date(date);d.setHours(0,0,0,0);return Math.max(0,Math.min(364,Math.round((d-PLAN_START)/DAY_MS)))}
function dateFromIndex(index){const d=new Date(PLAN_START);d.setDate(d.getDate()+Math.max(0,Math.min(364,index)));return d}
function setPlanDate(value){const d=value instanceof Date?new Date(value):new Date(`${value}T00:00:00`);if(Number.isNaN(d.getTime()))return;selectedPlanDate=d<PLAN_START?new Date(PLAN_START):d>PLAN_END?new Date(PLAN_END):d;render365();renderEnglish();renderMath();renderPolitics();renderFitness();renderNutrition()}
function phaseFor(i){if(i<=101)return{name:'阶段一 · 建立底盘',desc:'英语阅读与词汇每日不断线；数学以高数基础为核心；政治只做概念启蒙，不挤占数学英语。',start:0,end:101};if(i<=222)return{name:'阶段二 · 完成基础',desc:'数学完成高数、线代、概率基础框架并开始回收；英语提高精读强度；政治形成基础知识树。',start:102,end:222};if(i<=313)return{name:'阶段三 · 系统强化',desc:'数学进入综合题和章节训练；英语强化题型意识；政治由概念阅读转入课程与选择题理解。',start:223,end:313};return{name:'阶段四 · 暑期提升',desc:'以章节限时、错题二刷和讲义框架复述为主，为下一阶段正式考研复习建立高起点。',start:314,end:364}}
function englishFor(i){
 const article=window.ENGLISH_ARTICLES?.[Math.max(0,Math.min(364,i))];
 if(article)return{...article,meta:`${article.type} · ${article.source} · ${article.date||'日期见原文'} · ${article.words} 词`};
 return{title:'英语阅读内容暂未载入',meta:'请刷新页面或检查 english-articles.js',paragraphs:['今日文章库没有成功载入。'],long:'Please reload the page after confirming that the English article library is available.',analysis:'文章库未载入。',questions:['Please reload the page.'],answers:'文章库未载入。'}
}
function mathFor(i){
 const p=phaseFor(i),data=DAILY_DATA.mathTopics;let bank=p.start<102?data.foundation:p.start<223?[...data.foundation,...data.reinforce]:p.start<314?data.reinforce:data.advanced;
 const local=i-p.start,weeklyReview=dateFromIndex(i).getDay()===0,topic=weeklyReview?`周回收：${bank[Math.max(0,local-1)%bank.length]}`:bank[local%bank.length];
 const routes={zhangyu:'张宇课程路线',wuzhongxiang:'武忠祥课程路线',mixed:'武忠祥高数 + 自定义线代/概率'};
 const tasks=weeklyReview?[['框架复述','合上讲义，用15分钟写出本周知识树'],['错题二刷','选3道本周错题，不看答案重做'],['小测复盘','限时30分钟，按“概念/计算/审题”归因']]:[['课程视频','按所选路线学习45–75分钟，只记关键转折'],['讲义精读','整理定义条件、定理边界和2个典型题'],['独立练习','完成8–12题；卡住15分钟后再看解析']];
 return{topic,stage:p.name,route:routes[mathRoute]||routes.zhangyu,tasks,duration:weeklyReview?'75–100 min':'100–150 min'}
}
function politicsFor(i){
 const list=DAILY_DATA.politics,concept=list[(i*7+Math.floor(i/list.length))%list.length],round=Math.floor(i/list.length)+1;
 const duration={light:'15–20 min',normal:'30–40 min',intensive:'50–60 min'}[politicsMode];
 const tasks=politicsMode==='light'?[['概念阅读','读一遍并圈出3个关键词'],['主动回忆','不看原文，用两句话回答今日思考']]:politicsMode==='normal'?[['课程/文本','围绕今日概念学习20分钟'],['关系图','写出概念之间的两组关系'],['选择题意识','自拟一个易混干扰项并解释']]:[['课程视频','完成对应章节课程30–40分钟'],['教材回看','核对规范表述和逻辑层级'],['输出训练','完成5道选择题或150字概念说明']];
 return{...concept,round,duration,tasks}
}
function getDailyPlan(i){return{index:i,date:dateFromIndex(i),phase:phaseFor(i),english:englishFor(i),math:mathFor(i),politics:politicsFor(i)}}

function getCurrentWeek(){
 if(!settings.termStart) return null;
 const start=new Date(`${settings.termStart}T00:00:00`), now=new Date(); now.setHours(0,0,0,0);
 return Math.floor((now-start)/604800000)+1;
}
function parseWeeks(text){
 const cleaned=String(text||'').replace(/[，、\s]/g,',').replace(/第|周|单|双/g,''); const set=new Set();
 cleaned.split(',').filter(Boolean).forEach(part=>{const m=part.match(/^(\d+)\s*[-—~至]\s*(\d+)$/);if(m){let a=+m[1],b=+m[2];for(let i=Math.min(a,b);i<=Math.max(a,b);i++)set.add(i)}else if(/^\d+$/.test(part))set.add(+part)}); return [...set].sort((a,b)=>a-b);
}
function isActive(course,week){return parseWeeks(course.weeks).includes(+week)}
function coursesFor(day,week){return courses.filter(c=>+c.day===+day&&isActive(c,week)).sort((a,b)=>a.start-b.start)}
function navigate(id){document.querySelectorAll('.nav button,.view').forEach(x=>x.classList.remove('active'));document.querySelector(`.nav button[data-view="${id}"]`)?.classList.add('active');$(id).classList.add('active');if(id==='schedule')renderSchedule();if(id==='english')renderEnglish();if(id==='plan365')render365();if(id==='math')renderMath();if(id==='politics')renderPolitics();if(id==='fitness')renderFitness();if(id==='nutrition')renderNutrition();window.scrollTo({top:document.querySelector('.nav').offsetTop-8,behavior:'smooth'})}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>navigate(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));

function renderHeader(){
 const now=new Date(), cw=getCurrentWeek(); $('todayDate').textContent=`${now.getFullYear()}年${now.getMonth()+1}月${now.getDate()}日 · ${DAYS[now.getDay()]}`;
 $('currentWeek').textContent=cw&&cw>0&&cw<=settings.termWeeks?`${settings.termName||'本学期'} · 第${cw}周`:'未设置学期';
 const current=cw||viewWeekNumber; $('courseCount').textContent=courses.filter(c=>isActive(c,current)).length;
 $('wordDue').textContent=deck.filter(w=>w.status!=='new'&&w.due<=dateKey()).length;
}
function buildTodayTasks(){
 const now=new Date(), day=now.getDay(), week=getCurrentWeek()||viewWeekNumber, active=coursesFor(day,week), water=active.filter(c=>c.type==='water');
 const plan=getDailyPlan(planIndex(now)); const tasks=[];
 if(water.length) tasks.push({title:'利用可自习课程',detail:`${water.map(c=>c.name).join('、')}：背词或长难句 30–45 分钟`,tag:'英语'});
 const classLoad=active.reduce((n,c)=>n+(+c.end-+c.start+1),0);
 if(classLoad<=4) tasks.push({title:`数学 · ${plan.math.topic}`,detail:'课程/讲义 + 例题 + 练习，完成一个90–120分钟深度块',tag:'数学'}); else tasks.push({title:`数学保底 · ${plan.math.topic}`,detail:'只完成课程和基础例题，45–60分钟',tag:'数学'});
 tasks.push({title:`英语 · ${plan.english.title}`,detail:`阅读一篇 + 长难句 + 到期词 ${deck.filter(w=>w.status!=='new'&&w.due<=dateKey()).length} 个`,tag:'英语'});
 tasks.push({title:`政治 · ${plan.politics.title}`,detail:classLoad>6?'阅读概念卡并回答问题，15分钟':'阅读概念卡 + 课程/笔记，20–30分钟',tag:'政治'});
 if(active.length) tasks.push({title:'课程收口',detail:'核心内容、作业和疑问用 20 分钟归档',tag:'课程'});
 const fitness=fitnessInfoFor(now);if(fitness.type==='workout')tasks.push({title:fitness.muscle.title,detail:'按五日循环执行；可逐项打卡或顺延',tag:'训练'});else if(fitness.type==='rest')tasks.push({title:'训练恢复日',detail:'临时/固定休息，五日循环自动顺延',tag:'训练'});
 const energy=calculateEnergy();tasks.push({title:'饮食与恢复',detail:`今日热量目标约 ${energy.target} kcal，蛋白 130–150g，睡眠 7h+`,tag:'饮食'}); return tasks;
}
function renderToday(){
 const tasks=buildTodayTasks(), today=dateKey(), done=checks[today]||[]; $('todayTitle').textContent=`${DAYS[new Date().getDay()]}的最小闭环`;
 const cw=getCurrentWeek(); $('todayHint').textContent=cw?`系统正按第 ${cw} 周课表安排今天。课少时推进，课多时守住底线。`:'课程表尚未确定。先使用默认学习节奏，开学后设置学期并导入 PDF 即可自动适配。';
 $('todayTasks').innerHTML=tasks.map((t,i)=>`<div class="task ${done.includes(i)?'done':''}" data-index="${i}"><button class="task-check" aria-label="切换完成状态"></button><div class="task-copy"><b>${escapeHtml(t.title)}</b><span>${escapeHtml(t.detail)}</span></div><span class="tiny-tag">${t.tag}</span></div>`).join('');
 document.querySelectorAll('.task').forEach(el=>el.querySelector('.task-check').onclick=()=>{const i=+el.dataset.index,a=checks[today]||[];checks[today]=a.includes(i)?a.filter(x=>x!==i):[...a,i];write('tri-checks',checks);renderToday()});
 const pct=Math.round(done.length/tasks.length*100);$('percent').textContent=`${pct}%`;$('ring').style.setProperty('--p',`${pct}%`);$('streak').textContent=calcStreak();renderTodayCourses();
}
function calcStreak(){let n=0,d=new Date();for(let i=0;i<90;i++){if((checks[dateKey(d)]||[]).length)n++;else if(i>0)break;d.setDate(d.getDate()-1)}return n}
function renderTodayCourses(){
 const cw=getCurrentWeek()||viewWeekNumber, list=coursesFor(new Date().getDay(),cw);$('todayCourseMeta').textContent=courses.length?`第 ${cw} 周 · ${list.length} 门`:'尚未设置';
 $('todayCourses').innerHTML=list.length?list.map(c=>`<div class="compact-course ${c.type}"><b>${escapeHtml(c.name)}</b><span>第 ${c.start}–${c.end} 节 · ${escapeHtml(c.place||'地点未填')} · ${escapeHtml(c.weeks)}周</span></div>`).join(''):`<div class="empty">今天没有已录入课程。<br>可前往“动态课表”添加或导入。</div>`;
}
$('refreshToday').onclick=()=>{renderToday();toast('已根据当前课表重新生成')};

function syncPlanDates(){const value=dateKey(selectedPlanDate);['planDate','englishDate','mathDate','politicsDate','fitnessDate','nutritionDate'].forEach(id=>{$(id).value=value})}
function weekForDate(date){if(!settings.termStart)return null;const d=new Date(date);d.setHours(0,0,0,0);return Math.floor((d-new Date(`${settings.termStart}T00:00:00`))/604800000)+1}
function render365(){
 const plan=getDailyPlan(planIndex()),i=plan.index,key=dateKey(plan.date),done=planChecks[key]||[];syncPlanDates();$('planDayTitle').textContent=`第 ${i+1} 天 · ${key}`;$('yearProgressBar').style.width=`${(i+1)/365*100}%`;$('yearProgressText').textContent=`${i+1} / 365`;
 const cards=[{id:'english',cls:'english-card',name:'英语',title:plan.english.title,duration:'75–100 min',items:['完整来源阅读并完成3个问题','拆解原文长难句','复习到期词 + 15个新词']},{id:'math',cls:'math-card',name:'数学',title:plan.math.topic,duration:plan.math.duration,items:plan.math.tasks.map(x=>x[0]+'：'+x[1])},{id:'politics',cls:'politics-card',name:'政治',title:plan.politics.title,duration:plan.politics.duration,items:plan.politics.tasks.map(x=>x[0]+'：'+x[1])}];
 $('dailySubjects').innerHTML=cards.map(c=>`<article class="subject-day ${c.cls} ${done.includes(c.id)?'completed':''}"><div class="eyebrow">${c.name}</div><h3>${escapeHtml(c.title)}</h3><span class="duration">${c.duration}</span><ul>${c.items.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><div class="inline-actions"><button class="soft" data-open-subject="${c.id}">进入模块</button><button class="primary" data-check-subject="${c.id}">${done.includes(c.id)?'已完成 ✓':'今日完成'}</button></div></article>`).join('');
 document.querySelectorAll('[data-open-subject]').forEach(b=>b.onclick=()=>navigate(b.dataset.openSubject));document.querySelectorAll('[data-check-subject]').forEach(b=>b.onclick=()=>{const id=b.dataset.checkSubject,a=planChecks[key]||[];planChecks[key]=a.includes(id)?a.filter(x=>x!==id):[...a,id];write('tri-plan-checks',planChecks);render365()});
 const ph=plan.phase;$('currentPhaseName').textContent=ph.name;$('currentPhaseDesc').textContent=ph.desc;$('phaseDays').innerHTML=`<b>${i-ph.start+1}</b><span>本阶段第 ${i-ph.start+1} / ${ph.end-ph.start+1} 天</span>`;
}
function renderEnglish(){
 const e=englishFor(planIndex());syncPlanDates();$('dailyEnglishTitle').textContent=e.title;$('dailyEnglishMeta').innerHTML=`${dateKey(selectedPlanDate)} · ${escapeHtml(e.meta)}${e.url?` · <a href="${escapeAttr(e.url)}" target="_blank" rel="noopener">查看官方原文 ↗</a>`:''}`;$('dailyEnglishText').innerHTML=e.paragraphs.map(p=>`<p>${escapeHtml(p)}</p>`).join('');$('englishQuestions').innerHTML=`<ol>${e.questions.map(q=>`<li>${escapeHtml(q)}</li>`).join('')}</ol>`;$('readingAnswers').textContent=e.answers;$('readingAnswers').classList.add('hidden');$('dailyLongSentence').textContent=e.long;$('sentenceAnalysis').textContent=e.analysis;$('sentenceAnalysis').classList.add('hidden');loadSentenceNotes();renderEnglishStats();requestAnimationFrame(()=>loadInk('english'));
}
function renderStudyWeekdays(subject){const box=document.querySelector(`[data-weekdays="${subject}"]`),active=smartConfig[subject]?.weekdays||[];box.innerHTML=DAY_ORDER.map(d=>`<label><input type="checkbox" value="${d}" ${active.includes(d)?'checked':''}><span>${DAYS[d].replace('周','')}</span></label>`).join('')}
function catalogKind(name){const ext=name.split('.').pop().toLowerCase();if(['mp4','m4v','mov','webm','mkv','avi'].includes(ext))return'video';if(['pdf','doc','docx','ppt','pptx','txt','md'].includes(ext))return'note';return''}
function minutesFromName(name,kind){const m=name.match(/(?:\[|（|\()?\s*(\d{1,3})\s*(?:min|分钟)/i);return m?+m[1]:kind==='video'?45:20}
async function detectVideoMinutes(file){return new Promise(resolve=>{const estimated=minutesFromName(file.name,'video'),video=document.createElement('video'),url=URL.createObjectURL(file),finish=v=>{URL.revokeObjectURL(url);resolve(v)};const timer=setTimeout(()=>finish(estimated),3500);video.preload='metadata';video.onloadedmetadata=()=>{clearTimeout(timer);finish(Number.isFinite(video.duration)?Math.max(1,Math.round(video.duration/60)):estimated)};video.onerror=()=>{clearTimeout(timer);finish(estimated)};video.src=url})}
async function filesToCatalog(subject,files){const accepted=[];for(const file of files){const kind=catalogKind(file.name);if(!kind)continue;const path=file.webkitRelativePath||file._relativePath||file.name,id=uid(),minutes=kind==='video'?await detectVideoMinutes(file):20;accepted.push({id,subject,name:file.name,path,kind,minutes,size:file.size});sessionCourseFiles.set(id,file)}return accepted.sort((a,b)=>a.path.localeCompare(b.path,'zh-CN',{numeric:true}))}
async function scanDirectory(handle,prefix=''){let files=[];for await(const entry of handle.values()){const path=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.kind==='directory')files.push(...await scanDirectory(entry,path));else{const file=await entry.getFile();file._relativePath=path;files.push(file)}}return files}
async function saveDirectoryHandle(subject,handle){const db=await openFileDb();await new Promise((resolve,reject)=>{const tx=db.transaction('handles','readwrite');tx.objectStore('handles').put({id:subject,handle});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function getDirectoryHandle(subject){const db=await openFileDb(),row=await new Promise((resolve,reject)=>{const req=db.transaction('handles').objectStore('handles').get(subject);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return row?.handle}
async function importCourseFiles(subject,files,handle=null){if(!files.length)return toast('目录中没有可识别的视频或讲义');toast('正在识别课程与视频时长…');courseCatalog[subject]=await filesToCatalog(subject,files);write('tri-course-catalog',courseCatalog);if(handle)try{await saveDirectoryHandle(subject,handle)}catch{}buildSmartSchedule(subject);renderCatalogSummary(subject);subject==='math'?renderMath():renderPolitics();toast(`已导入 ${courseCatalog[subject].length} 个课程文件`)}
function renderCatalogSummary(subject){const items=courseCatalog[subject]||[],videos=items.filter(x=>x.kind==='video'),notes=items.filter(x=>x.kind==='note'),minutes=videos.reduce((n,x)=>n+x.minutes,0);$(`${subject}CatalogSummary`).innerHTML=items.length?`已识别 <b>${videos.length}</b> 个视频、<b>${notes.length}</b> 份讲义<br>视频约 ${Math.floor(minutes/60)} 小时 ${minutes%60} 分钟 · 当前计划 ${Object.keys(smartSchedules[subject]||{}).length} 个学习日`:'尚未导入课程目录'}
function createCourseSchedule(items,start,minutes,weekdays){const schedule={};let cursor=0,d=new Date(`${start}T00:00:00`);while(d<=PLAN_END&&cursor<items.length){if(weekdays.includes(d.getDay())){const key=dateKey(d),today=[];let used=0;while(cursor<items.length){const item=items[cursor],cost=item.minutes||20;if(today.length&&used+cost>minutes)break;today.push(item.id);used+=cost;cursor++;if(used>=minutes)break}schedule[key]=today}d.setDate(d.getDate()+1)}return{schedule,cursor}}
function buildSmartSchedule(subject){
 const start=$(`${subject}PlanStart`)?.value||smartConfig[subject].start,minutes=+$(`${subject}DailyMinutes`)?.value||smartConfig[subject].minutes,box=document.querySelector(`[data-weekdays="${subject}"]`),weekdays=box?[...box.querySelectorAll('input:checked')].map(x=>+x.value):smartConfig[subject].weekdays;
 if(!weekdays.length)return toast('请至少选择一个学习日');smartConfig[subject]={start,minutes,weekdays};write('tri-smart-config',smartConfig);const items=courseCatalog[subject]||[],built=createCourseSchedule(items,start,minutes,weekdays);smartSchedules[subject]=built.schedule;write('tri-smart-schedules',smartSchedules);renderCatalogSummary(subject);subject==='math'?renderMath():renderPolitics();toast(built.cursor<items.length?'已排至8月31日，仍有部分资源未排入':'智能课程表已生成')
}
function smartItemsFor(subject,key){const ids=smartSchedules[subject]?.[key]||[],items=courseCatalog[subject]||[];return ids.map(id=>items.find(x=>x.id===id)).filter(Boolean)}
function backlogFor(subject,key){const items=courseCatalog[subject]||[],scheduled=smartSchedules[subject]||{};return Object.keys(scheduled).filter(d=>d<key).sort().flatMap(d=>(scheduled[d]||[]).map(id=>items.find(x=>x.id===id))).filter(x=>x&&!courseProgress[x.id]).slice(0,2)}
async function openCourseFile(subject,item){try{let file=sessionCourseFiles.get(item.id);if(!file){const root=await getDirectoryHandle(subject);if(!root)throw 0;if(root.requestPermission&&await root.requestPermission({mode:'read'})!=='granted')throw 0;const parts=item.path.split('/');let dir=root;for(let i=0;i<parts.length-1;i++)dir=await dir.getDirectoryHandle(parts[i]);file=await(await dir.getFileHandle(parts.at(-1))).getFile()}const url=URL.createObjectURL(file);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),3600000)}catch{toast('请重新选择一次同步目录以恢复文件访问权限')}}
function renderImportedToday(subject){const key=dateKey(selectedPlanDate),today=smartItemsFor(subject,key),backlog=backlogFor(subject,key),all=[...backlog.map(x=>({...x,backlog:true})),...today.filter(x=>!backlog.some(b=>b.id===x.id))],box=$(`${subject}ImportedToday`);if(!all.length){box.innerHTML=courseCatalog[subject]?.length?'<div class="empty">今天没有排入的网盘课程。</div>':'';return}const total=all.reduce((n,x)=>n+(x.minutes||20),0);box.innerHTML=`<div class="course-total">网盘课程 ${all.length} 项 · 预计 ${total} 分钟</div>`+all.map(x=>`<div class="imported-course ${courseProgress[x.id]?'done':''}"><b>${x.backlog?'待回收 · ':''}${escapeHtml(x.name)}</b><span>${x.kind==='video'?'视频':'讲义'} · ${x.minutes}分钟 · ${escapeHtml(x.path)}</span><button data-open-course="${x.id}">打开文件</button><button data-complete-course="${x.id}">${courseProgress[x.id]?'已完成 ✓':'标记完成'}</button></div>`).join('');box.querySelectorAll('[data-open-course]').forEach(b=>b.onclick=()=>openCourseFile(subject,(courseCatalog[subject]||[]).find(x=>x.id===b.dataset.openCourse)));box.querySelectorAll('[data-complete-course]').forEach(b=>b.onclick=()=>{courseProgress[b.dataset.completeCourse]=!courseProgress[b.dataset.completeCourse];write('tri-course-progress',courseProgress);renderImportedToday(subject)})}
['math','politics'].forEach(subject=>{renderStudyWeekdays(subject);$(`${subject}PlanStart`).value=smartConfig[subject].start;$(`${subject}DailyMinutes`).value=smartConfig[subject].minutes;document.querySelector(`[data-build-smart="${subject}"]`).onclick=()=>buildSmartSchedule(subject);document.querySelector(`[data-pick-folder="${subject}"]`).onclick=async()=>{if(!window.showDirectoryPicker)return $(`${subject}FolderInput`).click();try{const handle=await window.showDirectoryPicker({mode:'read'}),files=await scanDirectory(handle);await importCourseFiles(subject,files,handle)}catch(e){if(e.name!=='AbortError')toast('目录读取失败，请使用兼容方式导入')}};$(`${subject}FolderInput`).onchange=e=>importCourseFiles(subject,[...e.target.files])});
function fitnessInfoFor(date){const start=new Date(`${fitnessSettings.start}T00:00:00`),target=new Date(date);target.setHours(0,0,0,0);if(target<start)return{type:'before',muscle:null};const key=dateKey(target),weekly=fitnessSettings.weeklyRest.includes(target.getDay());if(weekly||fitnessRest[key])return{type:'rest',reason:weekly?'固定休息日':fitnessRest[key],muscle:null};let active=0,d=new Date(start);while(d<target){const k=dateKey(d);if(!fitnessSettings.weeklyRest.includes(d.getDay())&&!fitnessRest[k])active++;d.setDate(d.getDate()+1)}return{type:'workout',muscle:MUSCLES[active%MUSCLES.length]}}
function renderFitnessWeekdays(){const box=$('fitnessWeekdays');box.innerHTML=DAY_ORDER.map(d=>`<label><input type="checkbox" value="${d}" ${fitnessSettings.weeklyRest.includes(d)?'checked':''}><span>${DAYS[d]}</span></label>`).join('')}
function fitnessExercises(muscle){return String(fitnessSettings.templates[muscle.id]||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function renderFitness(){
 syncPlanDates();$('fitnessStart').value=fitnessSettings.start;renderFitnessWeekdays();const info=fitnessInfoFor(selectedPlanDate),key=dateKey(selectedPlanDate),log=fitnessLogs[key]||{checks:[],complete:false,note:''};$('fitnessNote').value=log.note||'';
 const weekly=fitnessSettings.weeklyRest.includes(selectedPlanDate.getDay());$('toggleRest').disabled=weekly;$('toggleRest').textContent=weekly?'固定休息日':fitnessRest[key]?'取消临时休息':'设为临时休息';$('postponeWorkout').classList.toggle('hidden',info.type!=='workout');$('completeWorkout').classList.toggle('hidden',info.type!=='workout');
 if(info.type==='before'){$('fitnessMuscle').textContent='循环尚未开始';$('fitnessStatus').textContent=`训练循环从 ${fitnessSettings.start} 开始`;$('fitnessExerciseList').innerHTML='<div class="empty">可在右侧修改循环开始日期。</div>'}else if(info.type==='rest'){$('fitnessMuscle').textContent='恢复日';$('fitnessStatus').textContent=weekly?'固定休息星期；当天不推进五日循环。':info.reason==='postponed'?'训练已推迟，下一训练日继续当前部位。':'临时休息；后续部位自动顺延。';$('fitnessExerciseList').innerHTML='<div class="empty">散步、拉伸、正常饮食与睡眠即可。</div>'}else{const ex=fitnessExercises(info.muscle);$('fitnessMuscle').textContent=info.muscle.title;$('fitnessStatus').textContent=log.complete?'当天训练已完成 ✓':'完成动作后逐项打卡；临时休息不会跳过该部位。';$('fitnessExerciseList').innerHTML=ex.length?ex.map((x,i)=>`<div class="exercise-item ${log.checks.includes(i)?'done':''}" data-exercise="${i}"><button></button><span>${escapeHtml(x)}</span></div>`).join(''):'<div class="empty">尚未填写该部位动作，请在右侧编辑模板。</div>';document.querySelectorAll('[data-exercise]').forEach(el=>el.onclick=()=>{const i=+el.dataset.exercise,current=fitnessLogs[key]||{checks:[],complete:false,note:''};current.checks=current.checks.includes(i)?current.checks.filter(x=>x!==i):[...current.checks,i];fitnessLogs[key]=current;write('tri-fitness-logs',fitnessLogs);renderFitness()})}
 $('fitnessTemplateText').value=fitnessSettings.templates[$('fitnessTemplateSelect').value]||'';const preview=[];for(let j=0;j<10;j++){const d=new Date(selectedPlanDate);d.setDate(d.getDate()+j);const inf=fitnessInfoFor(d);preview.push(`<div class="cycle-day ${inf.type==='rest'?'rest':''}"><b>${d.getMonth()+1}/${d.getDate()}</b><span>${inf.muscle?.name||'休'}</span></div>`)}$('fitnessPreview').innerHTML=preview.join('')
}
$('fitnessTemplateSelect').onchange=e=>{fitnessSettings.templates[fitnessEditingMuscle]=$('fitnessTemplateText').value;fitnessEditingMuscle=e.target.value;$('fitnessTemplateText').value=fitnessSettings.templates[fitnessEditingMuscle]||''};$('saveFitnessSettings').onclick=()=>{fitnessSettings.start=$('fitnessStart').value;fitnessSettings.weeklyRest=[...$('fitnessWeekdays').querySelectorAll('input:checked')].map(x=>+x.value);fitnessSettings.templates[fitnessEditingMuscle]=$('fitnessTemplateText').value;write('tri-fitness-settings',fitnessSettings);renderFitness();renderToday();toast('训练循环设置已保存')};
$('fitnessNote').oninput=()=>{const key=dateKey(selectedPlanDate),log=fitnessLogs[key]||{checks:[],complete:false,note:''};log.note=$('fitnessNote').value;fitnessLogs[key]=log;write('tri-fitness-logs',fitnessLogs)};$('completeWorkout').onclick=()=>{const key=dateKey(selectedPlanDate),log=fitnessLogs[key]||{checks:[],note:''};log.complete=!log.complete;fitnessLogs[key]=log;write('tri-fitness-logs',fitnessLogs);renderFitness();toast(log.complete?'训练打卡完成':'已取消完成状态')};
$('postponeWorkout').onclick=()=>{const key=dateKey(selectedPlanDate);fitnessRest[key]='postponed';delete fitnessLogs[key];write('tri-fitness-rest',fitnessRest);write('tri-fitness-logs',fitnessLogs);renderFitness();renderToday();toast('训练已顺延至下一训练日')};$('toggleRest').onclick=()=>{const key=dateKey(selectedPlanDate);if(fitnessRest[key])delete fitnessRest[key];else fitnessRest[key]='rest';write('tri-fitness-rest',fitnessRest);renderFitness();renderToday();toast(fitnessRest[key]?'已设为临时休息':'已取消临时休息')};
const QUICK_FOODS=[{name:'鸡蛋 1个',cal:70,p:6,c:.5,f:5,type:'早餐'},{name:'牛奶 250ml',cal:150,p:8,c:12,f:8,type:'早餐'},{name:'香蕉 1根',cal:105,p:1.3,c:27,f:.4,type:'加餐'},{name:'米饭 200g',cal:232,p:5,c:52,f:.6,type:'午餐'},{name:'塑封鸡腿 1个',cal:180,p:20,c:5,f:9,type:'加餐'},{name:'燕麦 50g',cal:190,p:6.5,c:34,f:3.5,type:'早餐'}];
function calculateEnergy(){const p=nutritionProfile,rmr=10*p.weight+6.25*p.height-5*p.age+(p.sex==='male'?5:-161),tdee=rmr*p.activity,target=Math.max(1200,tdee-p.deficit);return{rmr:Math.round(rmr),tdee:Math.round(tdee),target:Math.round(target)}}
function foodEstimate(food,grams){const ratio=grams/100,cal=Math.round(food.kcal*ratio),variance=food.v||.15;return{cal,low:Math.max(0,Math.round(cal*(1-variance))),high:Math.round(cal*(1+variance)),p:+(food.p*ratio).toFixed(1),c:+(food.c*ratio).toFixed(1),f:+(food.f*ratio).toFixed(1)}}
function foodMatches(query){const q=query.trim().toLowerCase();if(!q)return FOOD_DATA.filter((_,i)=>i<12);return FOOD_DATA.map((food,i)=>({food,i,text:`${food.name} ${food.aliases} ${food.cat}`.toLowerCase()})).filter(x=>x.text.includes(q)).sort((a,b)=>(a.food.name===q?-5:0)-(b.food.name===q?-5:0)||a.food.name.length-b.food.name.length).slice(0,12).map(x=>x.food)}
function renderFoodSuggestions(query=$('foodSearch').value){const list=foodMatches(query);$('foodSuggestions').innerHTML=list.length?list.map(food=>`<button data-food-choice="${FOOD_DATA.indexOf(food)}">${escapeHtml(food.name)} <small>${food.kcal} kcal/100g</small></button>`).join(''):'<span class="muted">没有匹配菜品，可使用下方手动填写。</span>';document.querySelectorAll('[data-food-choice]').forEach(b=>b.onclick=()=>selectFood(FOOD_DATA[+b.dataset.foodChoice]))}
function selectFood(food){selectedFood=food;$('foodSearch').value=food.name;$('estimateGrams').value=food.serving;renderFoodSuggestions(food.name);renderSelectedFood()}
function renderSelectedFood(){if(!selectedFood)return;const grams=Math.max(1,+$('estimateGrams').value||selectedFood.serving),e=foodEstimate(selectedFood,grams);$('selectedFoodCategory').textContent=selectedFood.cat;$('selectedFoodName').textContent=selectedFood.name;$('selectedFoodMeta').textContent=`标准份约 ${selectedFood.serving}g（${selectedFood.portion}）· 每100g约${selectedFood.kcal}kcal`;$('estimateCalories').textContent=`约 ${e.cal} kcal`;$('estimateRange').textContent=`考虑烹调差异：${e.low}–${e.high} kcal`;$('estimateMacros').textContent=`蛋白 ${e.p}g · 碳水 ${e.c}g · 脂肪 ${e.f}g`}
function renderFoodEstimator(){const key=dateKey(selectedPlanDate);if(plateDate!==key){plateDate=key;plateDraft=[]}if(!selectedFood)selectedFood=FOOD_DATA.find(x=>x.name==='米饭')||FOOD_DATA[0];if(!$('foodSearch').value)$('foodSearch').value=selectedFood.name;if(!$('estimateGrams').value)$('estimateGrams').value=selectedFood.serving;renderFoodSuggestions($('foodSearch').value);renderSelectedFood()}
function renderPlate(){const total=plateDraft.reduce((n,x)=>n+x.cal,0),low=plateDraft.reduce((n,x)=>n+x.low,0),high=plateDraft.reduce((n,x)=>n+x.high,0);$('plateTotal').textContent=plateDraft.length?`约 ${total} kcal（${low}–${high}）`:'0 kcal';$('plateList').innerHTML=plateDraft.length?plateDraft.map(x=>`<div class="plate-item"><div><b>${escapeHtml(x.name)}</b><span>${x.grams}g · 蛋白${x.p}g / 碳水${x.c}g / 脂肪${x.f}g</span></div><strong>${x.cal} kcal</strong><button data-remove-plate="${x.id}">删除</button></div>`).join(''):'<div class="empty">搜索菜品并放入餐盘，可组合米饭、荤菜和蔬菜。</div>';document.querySelectorAll('[data-remove-plate]').forEach(b=>b.onclick=()=>{plateDraft=plateDraft.filter(x=>x.id!==b.dataset.removePlate);renderPlate()})}
$('foodSearch').oninput=e=>renderFoodSuggestions(e.target.value);$('estimateGrams').oninput=renderSelectedFood;document.querySelectorAll('[data-food-portion]').forEach(b=>b.onclick=()=>{if(!selectedFood)return;$('estimateGrams').value=Math.round(selectedFood.serving*+b.dataset.foodPortion);document.querySelectorAll('[data-food-portion]').forEach(x=>x.classList.toggle('primary',x===b));renderSelectedFood()});$('addToPlate').onclick=()=>{if(!selectedFood)return toast('请先选择菜品');const grams=Math.max(1,+$('estimateGrams').value||selectedFood.serving),e=foodEstimate(selectedFood,grams);plateDraft.push({id:uid(),name:selectedFood.name,grams,...e});renderPlate();toast('已放入本餐餐盘')};$('clearPlate').onclick=()=>{plateDraft=[];renderPlate()};$('savePlate').onclick=()=>{if(!plateDraft.length)return toast('餐盘还是空的');const type=$('plateMealType').value,key=dateKey(selectedPlanDate);mealLogs[key]=[...(mealLogs[key]||[]),...plateDraft.map(x=>({...x,id:uid(),type}))];write('tri-meal-logs',mealLogs);plateDraft=[];renderNutrition();renderToday();toast('整餐已写入今日记录')};
function renderNutrition(){
 syncPlanDates();$('profileSex').value=nutritionProfile.sex;$('profileAge').value=nutritionProfile.age;$('profileHeight').value=nutritionProfile.height;$('profileWeight').value=nutritionProfile.weight;$('activityFactor').value=nutritionProfile.activity;$('calorieDeficit').value=nutritionProfile.deficit;const energy=calculateEnergy(),key=dateKey(selectedPlanDate),meals=mealLogs[key]||[],sum=field=>meals.reduce((n,x)=>n+(+x[field]||0),0),cal=Math.round(sum('cal')),protein=sum('p'),carbs=sum('c'),fat=sum('f'),remaining=energy.target-cal;
 $('rmrValue').textContent=energy.rmr;$('tdeeValue').textContent=energy.tdee;$('calorieTarget').textContent=energy.target;$('calorieRemaining').textContent=remaining;$('calorieConsumed').textContent=cal;$('proteinTotal').textContent=`${protein.toFixed(1)} / ${Math.round(nutritionProfile.weight*1.8)}g`;$('carbTotal').textContent=`${carbs.toFixed(1)}g`;$('fatTotal').textContent=`${fat.toFixed(1)}g`;$('calorieDonut').style.setProperty('--p',`${Math.min(100,cal/energy.target*100)}%`);
 $('quickFoods').innerHTML='';renderFoodEstimator();renderPlate();
 $('mealList').innerHTML=meals.length?meals.map(x=>`<div class="meal-item"><span class="meal-tag">${escapeHtml(x.type)}</span><div><b>${escapeHtml(x.name)}</b><span>${x.grams?`${x.grams}g · `:''}蛋白 ${x.p||0}g · 碳水 ${x.c||0}g · 脂肪 ${x.f||0}g${x.low?` · 区间 ${x.low}–${x.high} kcal`:''}</span></div><strong>${x.cal} kcal</strong><button data-delete-meal="${x.id}">删除</button></div>`).join(''):'<div class="empty">今天还没有餐饮记录。</div>';document.querySelectorAll('[data-delete-meal]').forEach(b=>b.onclick=()=>{mealLogs[key]=meals.filter(x=>x.id!==b.dataset.deleteMeal);write('tri-meal-logs',mealLogs);renderNutrition()});
 const weeklyLoss=nutritionProfile.deficit*7/7700;$('nutritionAdvice').innerHTML=`采用 Mifflin–St Jeor 公式估算静息能量。当前缺口约对应每周 ${weeklyLoss.toFixed(2)} kg 的理论变化，但实际结果会受活动、记录误差和代谢适应影响。请看连续2–3周平均体重后每次只调整100–150 kcal。<br><br>食堂菜估算依据“每100g参考值 × 估计克重”，并按菜品用油差异给出区间。标准份只帮助判断分量，不代表建议摄入量；包装食品优先使用营养标签。<br><br><a href="https://pubmed.ncbi.nlm.nih.gov/2305711/" target="_blank" rel="noopener">静息代谢公式来源</a> · <a href="https://www.niddk.nih.gov/health-information/weight-management/just-enough-food-portions" target="_blank" rel="noopener">NIDDK分量说明</a>`;
}
function addMealEntry(item){const key=dateKey(selectedPlanDate);mealLogs[key]=[...(mealLogs[key]||[]),item];write('tri-meal-logs',mealLogs);renderNutrition();renderToday();toast('已加入今日餐饮')}
$('calculateCalories').onclick=()=>{nutritionProfile={sex:$('profileSex').value,age:+$('profileAge').value,height:+$('profileHeight').value,weight:+$('profileWeight').value,activity:+$('activityFactor').value,deficit:+$('calorieDeficit').value};write('tri-nutrition-profile',nutritionProfile);renderNutrition();renderToday();toast('热量目标已更新')};$('addMeal').onclick=()=>{const name=$('foodName').value.trim(),cal=+$('foodCalories').value;if(!name||!cal)return toast('请填写食物名称和热量');addMealEntry({id:uid(),type:$('mealType').value,name,cal,p:+$('foodProtein').value||0,c:+$('foodCarbs').value||0,f:+$('foodFat').value||0});['foodName','foodCalories','foodProtein','foodCarbs','foodFat'].forEach(id=>$(id).value='')};
function renderMath(){
 const m=mathFor(planIndex()),imported=smartItemsFor('math',dateKey(selectedPlanDate));syncPlanDates();$('mathRoute').value=mathRoute;$('mathTopic').textContent=imported[0]?.name||m.topic;$('mathStage').textContent=`${dateKey(selectedPlanDate)} · ${m.stage} · ${m.route} · 建议 ${m.duration}`;$('mathTasks').innerHTML=m.tasks.map((x,i)=>`<div class="module-task"><i>${i+1}</i><div><b>${x[0]}</b><span>${x[1]}</span></div></div>`).join('');$('mathNote').value=localStorage.getItem(`tri-note-math-${dateKey(selectedPlanDate)}`)||'';renderCatalogSummary('math');renderImportedToday('math');renderResources('math');renderStoredFiles('math');requestAnimationFrame(()=>loadInk('math'));
}
function renderPolitics(){
 const p=politicsFor(planIndex()),imported=smartItemsFor('politics',dateKey(selectedPlanDate));syncPlanDates();$('politicsMode').value=politicsMode;$('politicsTitle').textContent=imported[0]?.name||`${p.title} · 第${p.round}轮`;$('politicsText').textContent=p.text;$('politicsQuestion').textContent=p.q;$('politicsTasks').innerHTML=p.tasks.map((x,i)=>`<div class="module-task"><i>${i+1}</i><div><b>${x[0]}</b><span>${x[1]}</span></div></div>`).join('');$('politicsNote').value=localStorage.getItem(`tri-note-politics-${dateKey(selectedPlanDate)}`)||'';renderCatalogSummary('politics');renderImportedToday('politics');renderResources('politics');renderStoredFiles('politics');requestAnimationFrame(()=>loadInk('politics'));
}
document.querySelectorAll('[data-plan-prev]').forEach(b=>b.onclick=()=>setPlanDate(dateFromIndex(planIndex()-1)));document.querySelectorAll('[data-plan-next]').forEach(b=>b.onclick=()=>setPlanDate(dateFromIndex(planIndex()+1)));['planDate','englishDate','mathDate','politicsDate','fitnessDate','nutritionDate'].forEach(id=>$(id).onchange=e=>setPlanDate(e.target.value));
document.querySelectorAll('[data-nutrition-prev]').forEach(b=>b.onclick=()=>setPlanDate(dateFromIndex(planIndex()-1)));document.querySelectorAll('[data-nutrition-next]').forEach(b=>b.onclick=()=>setPlanDate(dateFromIndex(planIndex()+1)));
$('showReadingAnswers').onclick=()=>$('readingAnswers').classList.toggle('hidden');$('showSentenceAnalysis').onclick=()=>$('sentenceAnalysis').classList.toggle('hidden');
$('mathRoute').onchange=e=>{mathRoute=e.target.value;localStorage.setItem('tri-math-route',mathRoute);renderMath();render365()};$('politicsMode').onchange=e=>{politicsMode=e.target.value;localStorage.setItem('tri-politics-mode',politicsMode);renderPolitics();render365()};
$('mathNote').oninput=()=>localStorage.setItem(`tri-note-math-${dateKey(selectedPlanDate)}`,$('mathNote').value);$('politicsNote').oninput=()=>localStorage.setItem(`tri-note-politics-${dateKey(selectedPlanDate)}`,$('politicsNote').value);

function renderResources(subject){
 const box=$(`${subject}Resources`),items=resources.filter(r=>r.subject===subject);box.innerHTML=items.map(r=>`<div class="resource-item"><div><b>${escapeHtml(r.name)}</b><span>${escapeHtml(r.url)}</span></div><a href="${escapeAttr(r.url)}" target="_blank" rel="noopener">打开</a><button data-delete-resource="${r.id}">删除</button></div>`).join('')+(items.length?'':'<div class="empty">尚未添加课程链接。</div>');box.querySelectorAll('[data-delete-resource]').forEach(b=>b.onclick=()=>{resources=resources.filter(r=>r.id!==b.dataset.deleteResource);write('tri-resources',resources);renderResources(subject)})
}
document.querySelectorAll('[data-add-resource]').forEach(b=>b.onclick=()=>{const subject=b.dataset.addResource,name=$(`${subject}ResourceName`).value.trim(),url=$(`${subject}ResourceUrl`).value.trim();if(!name||!/^https?:\/\//i.test(url))return toast('请填写名称和以 http 开头的合法链接');resources.push({id:uid(),subject,name,url});write('tri-resources',resources);$(`${subject}ResourceName`).value='';$(`${subject}ResourceUrl`).value='';renderResources(subject);toast('资源链接已保存')});

function openFileDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open('tri-study-files',3);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('files'))req.result.createObjectStore('files',{keyPath:'id'});if(!req.result.objectStoreNames.contains('handles'))req.result.createObjectStore('handles',{keyPath:'id'});if(!req.result.objectStoreNames.contains('ink'))req.result.createObjectStore('ink',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function storeStudyFile(subject,file){const db=await openFileDb();await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put({id:uid(),subject,name:file.name,type:file.type,blob:file,created:Date.now()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function listStudyFiles(subject){const db=await openFileDb(),all=await new Promise((resolve,reject)=>{const req=db.transaction('files').objectStore('files').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return all.filter(x=>x.subject===subject)}
async function deleteStudyFile(id){const db=await openFileDb();await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function renderStoredFiles(subject){try{const box=$(`${subject}Resources`),files=await listStudyFiles(subject);files.forEach(f=>{const el=document.createElement('div');el.className='resource-item';el.innerHTML=`<div><b>${escapeHtml(f.name)}</b><span>保存在当前浏览器 · 本地讲义</span></div><button data-open>打开</button><button data-del>删除</button>`;el.querySelector('[data-open]').onclick=()=>{const url=URL.createObjectURL(f.blob);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)};el.querySelector('[data-del]').onclick=async()=>{await deleteStudyFile(f.id);renderResources(subject);renderStoredFiles(subject)};box.appendChild(el)})}catch{}}
['math','politics'].forEach(subject=>{$(`${subject}File`).onchange=async e=>{const file=e.target.files[0];if(!file)return;try{await storeStudyFile(subject,file);renderResources(subject);await renderStoredFiles(subject);toast('本地讲义已保存')}catch{toast('文件保存失败，可能超过浏览器容量限制')}}});
async function getInkRecord(id){const db=await openFileDb(),row=await new Promise((resolve,reject)=>{const req=db.transaction('ink').objectStore('ink').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return row}
async function saveInk(subject){const state=inkState[subject];if(!state.key)return;try{const db=await openFileDb();await new Promise((resolve,reject)=>{const tx=db.transaction('ink','readwrite');tx.objectStore('ink').put({id:state.key,strokes:state.strokes,updated:Date.now()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch{toast('手写笔记保存失败') }}
function inkCanvas(subject){return $(`${subject}Ink`)}
function resizeInk(subject){const canvas=inkCanvas(subject),rect=canvas.getBoundingClientRect();if(rect.width<10)return false;const ratio=Math.max(1,window.devicePixelRatio||1),w=Math.round(rect.width*ratio),h=Math.round(rect.height*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}return true}
function redrawInk(subject){const canvas=inkCanvas(subject);if(!resizeInk(subject))return;const ctx=canvas.getContext('2d'),ratio=Math.max(1,window.devicePixelRatio||1),w=canvas.width/ratio,h=canvas.height/ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);for(const stroke of inkState[subject].strokes){if(stroke.points.length<1)continue;ctx.save();ctx.globalCompositeOperation=stroke.tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=stroke.color;ctx.lineWidth=stroke.tool==='eraser'?stroke.width*4:stroke.width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();stroke.points.forEach((p,i)=>{const x=p.x*w,y=p.y*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});if(stroke.points.length===1)ctx.lineTo(stroke.points[0].x*w+.1,stroke.points[0].y*h+.1);ctx.stroke();ctx.restore()}}
function bindInk(subject){const canvas=inkCanvas(subject),state=inkState[subject];if(canvas.dataset.inkBound)return;canvas.dataset.inkBound='1';const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)),pressure:e.pressure||.5}};canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture?.(e.pointerId);state.active={tool:state.tool,color:state.color,width:state.width,points:[point(e)]};state.strokes.push(state.active);redrawInk(subject)};canvas.onpointermove=e=>{if(!state.active)return;e.preventDefault();state.active.points.push(point(e));redrawInk(subject)};const finish=()=>{if(!state.active)return;state.active=null;saveInk(subject)};canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onpointerleave=e=>{if(e.buttons===0)finish()}}
async function loadInk(subject){const canvas=inkCanvas(subject);if(!resizeInk(subject))return;bindInk(subject);const key=`${subject}-${dateKey(selectedPlanDate)}`,state=inkState[subject];if(state.key!==key){state.key=key;try{state.strokes=(await getInkRecord(key))?.strokes||[]}catch{state.strokes=[]}}redrawInk(subject)}
document.querySelectorAll('[data-ink-tool]').forEach(b=>b.onclick=()=>{const subject=b.dataset.inkSubject;inkState[subject].tool=b.dataset.inkTool;document.querySelectorAll(`[data-ink-tool][data-ink-subject="${subject}"]`).forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('[data-ink-color]').forEach(x=>x.oninput=()=>{inkState[x.dataset.inkColor].color=x.value;inkState[x.dataset.inkColor].tool='pen'});document.querySelectorAll('[data-ink-width]').forEach(x=>x.oninput=()=>inkState[x.dataset.inkWidth].width=+x.value);document.querySelectorAll('[data-ink-undo]').forEach(b=>b.onclick=()=>{const s=b.dataset.inkUndo;inkState[s].strokes.pop();redrawInk(s);saveInk(s)});document.querySelectorAll('[data-ink-clear]').forEach(b=>b.onclick=()=>{const s=b.dataset.inkClear;if(confirm('清空当天这块手写板吗？')){inkState[s].strokes=[];redrawInk(s);saveInk(s)}});document.querySelectorAll('[data-ink-export]').forEach(b=>b.onclick=()=>{const s=b.dataset.inkExport,canvas=inkCanvas(s),out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const ctx=out.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(canvas,0,0);const a=document.createElement('a');a.href=out.toDataURL('image/png');a.download=`${s}-${dateKey(selectedPlanDate)}-notes.png`;a.click()});window.addEventListener('resize',()=>['english','math','politics'].forEach(redrawInk));

function renderSchedule(){
 viewWeekNumber=Math.max(1,Math.min(+settings.termWeeks||30,viewWeekNumber));$('viewWeek').textContent=`第 ${viewWeekNumber} 周`;
 const periods=+settings.periodCount||12, cols=8; let html=`<div class="tt-head" style="grid-column:1;grid-row:1">节次</div>`;
 DAY_ORDER.forEach((d,i)=>html+=`<div class="tt-head" style="grid-column:${i+2};grid-row:1">${DAYS[d]}</div>`);
 for(let p=1;p<=periods;p++){html+=`<div class="tt-time" style="grid-column:1;grid-row:${p+1}">第 ${p} 节</div>`;DAY_ORDER.forEach((d,i)=>html+=`<div class="tt-cell" style="grid-column:${i+2};grid-row:${p+1}"></div>`)}
 courses.filter(c=>isActive(c,viewWeekNumber)).forEach(c=>{const col=DAY_ORDER.indexOf(+c.day)+2,span=Math.max(1,+c.end-+c.start+1);html+=`<div class="course-block ${c.type}" data-id="${c.id}" style="grid-column:${col};grid-row:${+c.start+1};height:${span*52-6}px;z-index:3"><b>${escapeHtml(c.name)}</b><span>${c.start}-${c.end}节 · ${escapeHtml(c.place||'')}</span></div>`});
 const tt=$('timetable');tt.style.gridTemplateColumns=`70px repeat(7,minmax(112px,1fr))`;tt.style.gridTemplateRows=`42px repeat(${periods},52px)`;tt.innerHTML=html;document.querySelectorAll('.course-block').forEach(el=>el.onclick=()=>openCourse(el.dataset.id));
}
$('prevWeek').onclick=()=>{viewWeekNumber--;renderSchedule()};$('nextWeek').onclick=()=>{viewWeekNumber++;renderSchedule()};
function openCourse(id=''){
 const c=courses.find(x=>x.id===id);$('courseForm').reset();$('courseId').value=c?.id||'';$('courseDialogTitle').textContent=c?'编辑课程':'添加课程';$('deleteCourse').classList.toggle('hidden',!c);
 $('courseName').value=c?.name||'';$('courseDay').value=c?.day??1;$('courseType').value=c?.type||'normal';$('startPeriod').value=c?.start||1;$('endPeriod').value=c?.end||2;$('courseWeeks').value=c?.weeks||`1-${settings.termWeeks||18}`;$('coursePlace').value=c?.place||'';$('courseDialog').showModal();
}
$('addCourseBtn').onclick=()=>openCourse();
$('courseForm').onsubmit=e=>{e.preventDefault();const start=+$('startPeriod').value,end=+$('endPeriod').value,weeks=$('courseWeeks').value.trim();if(end<start||!parseWeeks(weeks).length){toast('请检查节次或周次格式');return}const obj={id:$('courseId').value||uid(),name:$('courseName').value.trim(),day:+$('courseDay').value,type:$('courseType').value,start,end,weeks,place:$('coursePlace').value.trim()};courses=courses.filter(c=>c.id!==obj.id);courses.push(obj);write('tri-courses',courses);$('courseDialog').close();renderAll();toast('课程已保存')};
$('deleteCourse').onclick=()=>{const id=$('courseId').value;if(confirm('确定删除这门课程吗？')){courses=courses.filter(c=>c.id!==id);write('tri-courses',courses);$('courseDialog').close();renderAll();toast('课程已删除')}};
$('termBtn').onclick=()=>{$('termName').value=settings.termName||'';$('termStart').value=settings.termStart||'';$('termWeeks').value=settings.termWeeks||18;$('periodCount').value=settings.periodCount||12;$('termDialog').showModal()};
$('termForm').onsubmit=e=>{e.preventDefault();settings={termName:$('termName').value.trim(),termStart:$('termStart').value,termWeeks:+$('termWeeks').value,periodCount:+$('periodCount').value};write('tri-settings',settings);viewWeekNumber=getCurrentWeek()||1;$('termDialog').close();renderAll();toast('学期设置已更新')};

function loadPdfJs(){
 return new Promise((resolve,reject)=>{if(window.pdfjsLib)return resolve(window.pdfjsLib);const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=()=>{pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';resolve(pdfjsLib)};s.onerror=()=>reject(new Error('PDF 识别组件加载失败，请检查网络后重试'));document.head.appendChild(s)});
}
$('pdfBtn').onclick=()=>{$('pdfStatus').textContent='';$('pdfCandidates').innerHTML='';$('pdfTextBox').classList.add('hidden');$('pdfTextPreview').value='';$('importCandidates').classList.add('hidden');$('pdfDialog').showModal()};$('closePdf').onclick=$('cancelPdf').onclick=()=>$('pdfDialog').close();
$('pdfInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('pdfStatus').textContent='正在读取 PDF…';try{const lib=await loadPdfJs(),data=await file.arrayBuffer(),pdf=await lib.getDocument({data}).promise;let lines=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent(),groups={};content.items.forEach(it=>{const y=Math.round(it.transform[5]/3)*3;(groups[y]||(groups[y]=[])).push({x:it.transform[4],s:it.str})});Object.keys(groups).sort((a,b)=>b-a).forEach(y=>lines.push(groups[y].sort((a,b)=>a.x-b.x).map(x=>x.s).join(' ').replace(/\s+/g,' ').trim()))}pdfDrafts=parsePdfLines(lines);$('pdfTextPreview').value=lines.filter(Boolean).join('\n');$('pdfTextBox').classList.remove('hidden');renderPdfCandidates(lines.length);$('pdfStatus').textContent=`已读取 ${pdf.numPages} 页、${lines.length} 行文字，找到 ${pdfDrafts.length} 条候选课程。`;if(!pdfDrafts.length)$('pdfStatus').innerHTML+=' 当前 PDF 可能是扫描图片或特殊表格，可展开提取文字并整理后重新解析。'}catch(err){$('pdfStatus').textContent=`${err.message}。你仍可使用手动添加课程。`}};
function parsePdfLines(lines){
 const dayMap={'一':1,'二':2,'三':3,'四':4,'五':5,'六':6,'日':0,'天':0},out=[];
 lines.forEach(line=>{if(!/(周|星期)[一二三四五六日天]/.test(line)||!/(节|课)/.test(line))return;const dayChar=(line.match(/(?:周|星期)([一二三四五六日天])/)||[])[1];if(!dayChar)return;const week=(line.match(/(?:第)?([0-9，、,\-—~至 ]{1,24})周/)||[])[1]?.replace(/[，、 ]/g,',').replace(/[—~至]/g,'-')||`1-${settings.termWeeks||18}`;const per=line.match(/第?\s*(\d+)\s*(?:[-—~至]\s*(\d+))?\s*节/);let name=line.replace(/(?:周|星期)[一二三四五六日天]/g,' ').replace(/(?:第)?[0-9，、,\-—~至 ]+周/g,' ').replace(/第?\s*\d+\s*(?:[-—~至]\s*\d+)?\s*节/g,' ').replace(/[|｜()（）\[\]]/g,' ').replace(/\s+/g,' ').trim();name=name.split(/教师|地点|教室/)[0].trim();if(name.length>2)out.push({id:uid(),name:name.slice(0,40),day:dayMap[dayChar],weeks:week,start:+(per?.[1]||1),end:+(per?.[2]||per?.[1]||2),type:'normal',place:''})});
 return out.filter((x,i,a)=>a.findIndex(y=>y.name===x.name&&y.day===x.day&&y.start===x.start)===i).slice(0,50);
}
$('parsePdfText').onclick=()=>{pdfDrafts=parsePdfLines($('pdfTextPreview').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean));renderPdfCandidates();$('pdfStatus').textContent=`重新解析完成，找到 ${pdfDrafts.length} 条候选课程。`;if(!pdfDrafts.length)toast('请按示例格式整理，每门课程一行')};
function renderPdfCandidates(lineCount){
 $('pdfCandidates').innerHTML=pdfDrafts.map((c,i)=>`<div class="candidate"><input type="checkbox" class="candidate-check" data-i="${i}" checked><label>课程名<input class="candidate-name" data-i="${i}" value="${escapeAttr(c.name)}"></label><label>星期<select class="candidate-day" data-i="${i}">${DAY_ORDER.map(d=>`<option value="${d}" ${d===c.day?'selected':''}>${DAYS[d]}</option>`).join('')}</select></label><label>周次<input class="candidate-weeks" data-i="${i}" value="${escapeAttr(c.weeks)}"></label><label>节次<input class="candidate-period" data-i="${i}" value="${c.start}-${c.end}"></label></div>`).join('');$('importCandidates').classList.toggle('hidden',!pdfDrafts.length);
}
$('importCandidates').onclick=()=>{const selected=[];document.querySelectorAll('.candidate-check:checked').forEach(box=>{const i=+box.dataset.i,c={...pdfDrafts[i]};c.name=document.querySelector(`.candidate-name[data-i="${i}"]`).value.trim();c.day=+document.querySelector(`.candidate-day[data-i="${i}"]`).value;c.weeks=document.querySelector(`.candidate-weeks[data-i="${i}"]`).value.trim();const p=document.querySelector(`.candidate-period[data-i="${i}"]`).value.match(/(\d+)\D+(\d+)/);if(p){c.start=+p[1];c.end=+p[2]}if(c.name&&parseWeeks(c.weeks).length)selected.push(c)});courses.push(...selected);write('tri-courses',courses);$('pdfDialog').close();renderAll();toast(`已导入 ${selected.length} 门课程`)};

function dueQueue(){const today=dateKey(),due=deck.filter(w=>w.status!=='new'&&(!w.due||w.due<=today)),fresh=deck.filter(w=>w.status==='new').slice(0,15);return [...due,...fresh]}
function renderEnglishStats(){$('wordDue').textContent=deck.filter(w=>w.status!=='new'&&w.due<=dateKey()).length;$('deckStat').textContent=`已学 ${deck.filter(w=>w.status!=='new').length} / ${deck.length}`}
function startWordSession(){wordQueue=dueQueue();wordIndex=0;if(!wordQueue.length){$('cardLabel').textContent='今日完成';$('wordText').textContent='Great work!';$('phonetic').textContent='没有到期词，明天再来';$('revealWord').classList.add('hidden');$('wordActions').classList.add('hidden');return}showWord()}
function showWord(){currentWord=wordQueue[wordIndex];if(!currentWord){startWordSession();return}$('cardLabel').textContent=`今日 ${wordIndex+1} / ${wordQueue.length}`;$('wordText').textContent=currentWord.word;$('phonetic').textContent=currentWord.phonetic||'';$('meaning').textContent=currentWord.meaning;$('example').textContent=currentWord.example||'';$('meaning').classList.add('hidden');$('example').classList.add('hidden');$('wordActions').classList.add('hidden');$('revealWord').classList.remove('hidden');$('revealWord').textContent='显示释义'}
function revealWord(){$('meaning').classList.remove('hidden');$('example').classList.toggle('hidden',!currentWord?.example);$('wordActions').classList.remove('hidden');$('revealWord').classList.add('hidden')}
$('startWords').onclick=startWordSession;$('revealWord').onclick=e=>{e.stopPropagation();revealWord()};$('wordCard').onclick=e=>{if(currentWord&&e.target.id!=='revealWord')revealWord()};
document.querySelectorAll('.word-actions button').forEach(b=>b.onclick=()=>{if(!currentWord)return;const score=+b.dataset.score,days=[1,3,7][score],due=new Date();due.setDate(due.getDate()+days);const i=deck.findIndex(w=>w.id===currentWord.id);deck[i]={...deck[i],status:'learning',due:dateKey(due),reps:(deck[i].reps||0)+1};write('tri-word-deck',deck);wordIndex++;if(wordIndex>=wordQueue.length){wordQueue=[];$('cardLabel').textContent='今日完成';$('wordText').textContent='Well done';$('phonetic').textContent='复习记录已保存';$('meaning').classList.add('hidden');$('example').classList.add('hidden');$('wordActions').classList.add('hidden');$('revealWord').classList.add('hidden');toast('今日单词完成')}else showWord();renderEnglishStats();renderToday()});
$('addWordBtn').onclick=()=>$('wordDialog').showModal();$('wordForm').onsubmit=e=>{e.preventDefault();deck.push({id:uid(),word:$('newWord').value.trim(),phonetic:$('newPhonetic').value.trim(),meaning:$('newMeaning').value.trim(),example:$('newExample').value.trim(),status:'new',due:'',reps:0});write('tri-word-deck',deck);$('wordForm').reset();$('wordDialog').close();renderEnglishStats();toast('已加入个人词库')};
let timerSeconds=1500,timerId=null;function renderTimer(){const m=Math.floor(timerSeconds/60),s=timerSeconds%60;$('timer').textContent=`${pad(m)}:${pad(s)}`}
$('timerBtn').onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;$('timerBtn').textContent='继续'}else{timerId=setInterval(()=>{timerSeconds--;renderTimer();if(timerSeconds<=0){clearInterval(timerId);timerId=null;$('timerBtn').textContent='开始';toast('专注 25 分钟完成') }},1000);$('timerBtn').textContent='暂停'}};$('timerReset').onclick=()=>{clearInterval(timerId);timerId=null;timerSeconds=1500;renderTimer();$('timerBtn').textContent='开始'};
function loadSentenceNotes(){const key=dateKey(selectedPlanDate),daily=englishFor(planIndex());$('sentenceOriginal').value=localStorage.getItem(`tri-sentenceOriginal-${key}`)||daily.long;['sentenceCore','sentenceClause','sentenceTranslation'].forEach(id=>{$(id).value=localStorage.getItem(`tri-${id}-${key}`)||''})}
['sentenceOriginal','sentenceCore','sentenceClause','sentenceTranslation'].forEach(id=>{$(id).oninput=()=>localStorage.setItem(`tri-${id}-${dateKey(selectedPlanDate)}`,$(id).value)});

function renderRoad(i=0){$('road').innerHTML=phases[i].map((x,j)=>`<article class="road-card"><div class="num">0${j+1}</div><h3>${x.name}</h3><div class="muted">${x.goal}</div><ul>${x.items.map(v=>`<li>${v}</li>`).join('')}</ul></article>`).join('')}
document.querySelectorAll('.phase').forEach(b=>b.onclick=()=>{document.querySelectorAll('.phase').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRoad(+b.dataset.phase)});
function renderHistory(){const logs=read('tri-logs',[]);$('history').innerHTML=logs.length?`<div class="history-row"><b>日期</b><b>均重</b><b>学习</b><b>训练</b><b>引体</b><b>单词</b></div>`+logs.slice().reverse().map(x=>`<div class="history-row"><span>${x.date}</span><span>${x.weight||'—'}kg</span><span>${x.hours||'—'}h</span><span>${x.workouts||'—'}次</span><span>${x.pullups||'—'}次</span><span>${x.words||'—'}个</span></div>`).join(''):`<div class="empty">还没有记录，建议每周日更新一次。</div>`}
$('saveLog').onclick=()=>{if(!$('logDate').value)return toast('请先选择日期');let logs=read('tri-logs',[]),obj={date:$('logDate').value,weight:$('weight').value,hours:$('hours').value,workouts:$('workouts').value,pullups:$('pullups').value,words:$('wordsLearned').value};logs=logs.filter(x=>x.date!==obj.date);logs.push(obj);logs.sort((a,b)=>a.date.localeCompare(b.date));write('tri-logs',logs);renderHistory();toast('周记录已保存')};
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function escapeAttr(s=''){return escapeHtml(s)}
function renderAll(){renderHeader();renderToday();renderSchedule();render365();renderEnglish();renderMath();renderPolitics();renderFitness();renderNutrition();renderHistory()}
// 只提供同一套普通网页界面；清理旧安装版注册，避免手机继续读取过期缓存。
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.getRegistrations().then(items=>items.forEach(item=>item.unregister())).catch(()=>{});
$('logDate').value=dateKey();renderRoad();renderTimer();renderAll();

